# Generated by Django 4.1.7 on 2023-03-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="submission",
            name="score_zero_or_hundred",
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="solution",
            new_name="answer",
        ),
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="problem",
                to="problems.answer",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="commentary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="problem",
                to="problems.commentary",
            ),
        ),
        migrations.AddConstraint(
            model_name="solution",
            constraint=models.CheckConstraint(
                check=models.Q(("score", 0), ("score", 100), _connector="OR"),
                name="score_zero_or_hundred_solution",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                check=models.Q(("score", 0), ("score", 100), _connector="OR"),
                name="score_zero_or_hundred_submission",
            ),
        ),
    ]
