# Generated by Django 4.1.7 on 2023-03-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_remove_submission_score_zero_or_hundred_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="problem",
                to="problems.answer",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="commentary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="problem",
                to="problems.commentary",
            ),
        ),
    ]
