# Generated by Django 4.1.7 on 2023-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_problem_answer_alter_problem_commentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
