# Generated by Django 4.1.7 on 2023-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_alter_solution_score_alter_submission_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
