# Generated by Django 4.1.7 on 2023-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_rename_category_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="state",
            field=models.CharField(
                choices=[
                    ("check_before", "Check Before"),
                    ("checking", "Checking"),
                    ("check_done", "Check Done"),
                ],
                default="check_before",
                max_length=12,
            ),
        ),
    ]
